#!/bin/bash

set -ex

# Don't push images if branch is not master
echo "Current Branch: $SOURCE_BRANCH"
if [ "${SOURCE_BRANCH}" != "master" ]; then
    exit 0
fi

for tag in $(docker images doomoolmori/scala-sbt-for-ci --format "{{.Tag}}");
do
    docker push "doomoolmori/scala-sbt-for-ci:${tag}"
done
